### ISSUE TITLE
<title>

### ISSUE THREAD

**Issue by alexmercerind** [AR-CADE/petit_player#1]
You could send us a PR implementing HLS support for web instead... Duh.

**Comment by AR-CADE** [comment]
Hi @alexmercerind,

for now the media_kit support in this library is in beta state, 
and i still have to figure out what exactly goes wrong with  media_kit and some kinds of long and complex HLS URLs ... because in those cases the video don't start, not only with flutter Web but also with flutter Linux.

i have not tested others platforms too,

But be sure when i'll have more time to test, and if i find something, i'll send you a PR. ;-)

**Comment by alexmercerind** [comment]
I wouldn't even call this a library but rather a wrapper. There is barely any value that it adds (while being GPL licensed, seriously?).

If one wants to have something serious for Flutter & Dart ecosystem, something reliable was needed from the ground-up. We've built media_kit from scratch to work on all platforms (mobile, desktop & web) & use performant hardware APIs (number of unit-tests are also in place). It also has way more features, better performance & wider API than video_player.

I still don't understand what purpose this "yet another layer of abstraction" which you created serves. Depending upon existing packages e.g. video_player_hls just degrades the overall quality between these abstractions. The better is to do it right from the start i.e. use HLS.js.
If I had time I would've already done it.

It's not like this is visually pleasing either... video controls in media_kit are already similar in quality to that of YouTube.
